# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true

# 레이블을 성공적으로 붙이고 PR에 보낼 코멘트를 설정
comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

# 레이블
labels:
  🐛 hotfix:
    - head-branch: ['^fix', 'fix']
  ✅ test:
    include:
      - '\btest\b'
  ✨ feat:
    - head-branch: ['^feat', 'feat']
  📝 docs:
    include:
      - '\bdocs\b'
  ♻️ refactor:
    - head-branch: ['^refactor', 'refactor']
  ⚙️ chore:
    - head-branch: ['^chore', 'chore']
