/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    colors: {
      black: '#000000',
      white: '#ffffff',
      gray: {
        0: 'var(--gray-color-0)',
        1: 'var(--gray-color-1)',
        5: 'var(--gray-color-5)',
        10: 'var(--gray-color-10)',
        20: 'var(--gray-color-20)',
        30: 'var(--gray-color-30)',
        40: 'var(--gray-color-40)',
        50: 'var(--gray-color-50)',
        60: 'var(--gray-color-60)',
        70: 'var(--gray-color-70)',
        80: 'var(--gray-color-80)',
        90: 'var(--gray-color-90)',
        95: 'var(--gray-color-95)',
        100: 'var(--gray-color-100)',
      },
      primary: {
        0: 'var(--primary-color-0)',
        1: 'var(--primary-color-1)',
        5: 'var(--primary-color-5)',
        10: 'var(--primary-color-10)',
        20: 'var(--primary-color-20)',
        30: 'var(--primary-color-30)',
        40: 'var(--primary-color-40)',
        50: 'var(--primary-color-50)',
        60: 'var(--primary-color-60)',
        70: 'var(--primary-color-70)',
        80: 'var(--primary-color-80)',
        90: 'var(--primary-color-90)',
        95: 'var(--primary-color-95)',
        99: 'var(--primary-color-99)',
      },
      calendar: {
        red: { DEFAULT: 'var(--calendar-color-red)', alt: 'var(--calendar-color-red-alt)' },
        yellow: { DEFAULT: 'var(--calendar-color-yellow)', alt: 'var(--calendar-color-yellow-alt)' },
        green: { DEFAULT: 'var(--calendar-color-green)', alt: 'var(--calendar-color-green-alt)' },
        blue: { DEFAULT: 'var(--calendar-color-blue)', alt: 'var(--calendar-color-blue-alt)' },
        purple: { DEFAULT: 'var(--calendar-color-purple)', alt: 'var(--calendar-color-purple-alt)' },
      },
      system: {
        background: 'var(--system-background)',
        warning: { DEFAULT: 'var(--system-warning)', alt: 'var(--system-warning-alt)' },
        safe: { DEFAULT: 'var(--system-safe)', alt: 'var(--system-safe-alt)' },
      },
    },
    extend: {
      zIndex: {
        base: 0,
        dropdown: 1000,
        sticky: 1020,
        fixed: 1030,
        'modal-overlay': 1040,
        modal: 1050,
        toast: 1060,
        tooltip: 1070,
      },
    },
  },
  plugins: [],
}
