name: PR labeler

on: pull_request
jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: actions/labeler@v5
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          sync-labels: true # 규칙에 맞지 않는 라벨 제거

