name: PR labeler

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened]
jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          sync-labels: true # 규칙에 맞지 않는 라벨 제거

